### ISSUE TITLE
[Refactor] - Move to atlas boxes for centos6 and 7

### ISSUE THREAD

**Issue by komidore64** [Katello/forklift#301]
[more info](https://github.com/beav/forklift/pull/8#discussion_r76834532)

possible downside is the official centos boxes don't allow root ssh access by default. 

hopefully won't be a problem with ansible though (e.g. - `become: true`)
### also
- [ ] update to users on how to clean up old box images and move to the new

**Comment by ekohl** [comment]
Currently the centos6 boxes are already broken because they can't access epel anymore (missing certificates or old SSL version I think) where the atlas boxes do work. For the centos7 boxes it also cleans things up because there are no redundant epel repo entries. I think the installer also broke on this. I'll come up with a patch for this.
